### ISSUE TITLE
Roadmap to v1.0.0

### ISSUE THREAD

**Issue by mrmlnc** [mrmlnc/yellfy-svg-sprite#5]
Make sprite from single SVG files and other sprites with ID attributes:

  - [x] Common
    - [x] Move the core in a separate repository. Name?
  - [x] API
    - [x] `sprite.collection([options])`
    - [x] `sprite.add(filename, content, [options])`
    - [x] `sprite.remove(filename)`
    - [x] `sprite.clean()`
    - [x] `sprite.compile()`
  - [ ] Parse SVG by `svg-parser`.
    - [ ] Support cache.
    - [x] ~~Get icons from SVG sprite with ID attributes.~~ (why?)
    - [x] Update ID attribute.
    - [x]  Resize icons.
    - [x] Add/Update custom icons attributes.
    - [x] Remove specified attributes.
    - [x] Remove extra attributes.
    - [x] Remove empty tags.
    - [x] Replace header for inline injecting to HTML.
    - [x] Add/Update parent attributes.
    - [x] Remove extra tags.
    - [x] Remove colors (`fill`, `style`, etc.)
  - [ ] Render SVG by `?`.
    - [x] Generate XML.
    - [x] ~~Prettify option.~~ (why?)
    - [x] ~~Write results to file.~~ (is not core function)
    - [ ] Generate CSS `?`.
